"""Fix UUID types in association tables

Revision ID: bd0668de4404
Revises: c5251fdb2d5c
Create Date: 2025-07-03 02:28:22.067017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0668de4404'
down_revision = 'c5251fdb2d5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(FALSE)'))
        batch_op.create_foreign_key(None, 'users', ['deleted_by'], ['id'])

    with op.batch_alter_table('snippet_collaborators', schema=None) as batch_op:
        batch_op.alter_column('snippet_id',
               existing_type=sa.INTEGER(),
               type_=app.models.custom_types.UUIDType(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=app.models.custom_types.UUIDType(),
               existing_nullable=False)

    with op.batch_alter_table('snippet_collections', schema=None) as batch_op:
        batch_op.alter_column('snippet_id',
               existing_type=sa.INTEGER(),
               type_=app.models.custom_types.UUIDType(),
               existing_nullable=False)
        batch_op.alter_column('collection_id',
               existing_type=sa.INTEGER(),
               type_=app.models.custom_types.UUIDType(),
               existing_nullable=False)

    with op.batch_alter_table('snippet_history', schema=None) as batch_op:
        batch_op.alter_column('snippet_id',
               existing_type=sa.INTEGER(),
               type_=app.models.custom_types.UUIDType(),
               existing_nullable=False)
        batch_op.alter_column('changed_by',
               existing_type=sa.INTEGER(),
               type_=app.models.custom_types.UUIDType(),
               existing_nullable=False)

    with op.batch_alter_table('snippet_shares', schema=None) as batch_op:
        batch_op.alter_column('snippet_id',
               existing_type=sa.INTEGER(),
               type_=app.models.custom_types.UUIDType(),
               existing_nullable=False)
        batch_op.alter_column('shared_by_id',
               existing_type=sa.INTEGER(),
               type_=app.models.custom_types.UUIDType(),
               existing_nullable=False)
        batch_op.alter_column('shared_with_id',
               existing_type=sa.INTEGER(),
               type_=app.models.custom_types.UUIDType(),
               existing_nullable=False)

    with op.batch_alter_table('snippets', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(FALSE)'))
        batch_op.alter_column('is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(FALSE)'))
        batch_op.create_foreign_key(None, 'users', ['deleted_by'], ['id'])

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.alter_column('invited_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('owner_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.alter_column('invited_by_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('snippets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(FALSE)'))
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(FALSE)'))
        batch_op.alter_column('team_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('snippet_shares', schema=None) as batch_op:
        batch_op.alter_column('shared_with_id',
               existing_type=app.models.custom_types.UUIDType(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('shared_by_id',
               existing_type=app.models.custom_types.UUIDType(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('snippet_id',
               existing_type=app.models.custom_types.UUIDType(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('snippet_history', schema=None) as batch_op:
        batch_op.alter_column('changed_by',
               existing_type=app.models.custom_types.UUIDType(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('snippet_id',
               existing_type=app.models.custom_types.UUIDType(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('snippet_collections', schema=None) as batch_op:
        batch_op.alter_column('collection_id',
               existing_type=app.models.custom_types.UUIDType(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('snippet_id',
               existing_type=app.models.custom_types.UUIDType(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('snippet_collaborators', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=app.models.custom_types.UUIDType(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('snippet_id',
               existing_type=app.models.custom_types.UUIDType(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(FALSE)'))

    # ### end Alembic commands ###
