"""Add description field to snippets

Revision ID: d5b9797869dc
Revises: 
Create Date: 2025-06-23 11:31:51.146281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b9797869dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snippets', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_snippets_code_hash'))
        batch_op.drop_column('code_hash')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('public_id')

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.alter_column('invited_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('owner_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.alter_column('invited_by_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('snippets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('code_hash', sa.VARCHAR(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_snippets_code_hash'), ['code_hash'], unique=False)
        batch_op.alter_column('team_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    # ### end Alembic commands ###
